### ISSUE TITLE
[bug report] cannot search contents after "."

### ISSUE THREAD

**Issue by augusttty** [CloudCannon/pagefind#267] opened 2023-04-10 16:01 UTC
page find seems couldn't recognize words after "." 
```html
   <h1>MyClass</h1>
   <h2>MyClass.doSomething()</h2>
   <p>This is a method, with descriptions here.</p>
```
When searching "doSomething", **pagefind** get empty result.
Must match prefix like "MyClass.doSom" to work.
Is it a bug?

**Comment by augusttty** [comment] 2023-04-10 16:05
## In official docs site:
![img](https://pixa.anomanm.com/temp/ewqjr.png)

**Comment by bglw** [comment] 2023-04-11 23:54
Hey @augusttty 👋 Not a bug per-se, but definitely a good improvement to be made here. The same general idea is being tracked in #225 where we should index this as `['pagefind.toml', 'pagefind', 'toml']`.

I'll close this thread but feel free to pick up any discussion in #225 🙂

**Closed by bglw** 2023-04-11 23:54 UTC
