### ISSUE TITLE
h1 title with <code> element not recognized

### ISSUE THREAD

**Issue by BryceRussell** [CloudCannon/pagefind#181] opened 2022-12-19 01:28 UTC
Some of my documentation pages have back ticks in the `h1` title like 
```
# `<Component>`
```
and the title does not get recognized for search results

**Comment by bglw** [comment] 2022-12-19 01:41
Ah, good find, this actually helps track down #67 — The issue is that the `<Component>` text isn't being correctly escaped by the Pagefind UI, so the browser is actually rendering it as `<component></component>`. I'll get this fixed up.

**Comment by bglw** [comment] 2022-12-19 01:45
For a quick fix, you could add a result hook to Pagefind:

```js
new PagefindUI({
    element: "#search",
    processResult: function (result) {
        result.meta.title = result.meta.title.replace(/</g, "&lt;").replace(/>/g, "&gt;")
        return result;
    }
});
```

**Comment by BryceRussell** [comment] 2022-12-19 02:46
It works! Thanks for the quick response, I was also having the same problems mentioned in #67 with some of my code blocks getting turned to HTML

**Comment by bglw** [comment] 2023-09-13 18:27
Hey @BryceRussell  ! 👋

Good news — this is fixed in Pagefind v1.0.0! ✨

See the full release notes here: https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0 💙

**Closed by bglw** 2023-09-13 18:27 UTC
Labels: bug, Pagefind UI
